### ISSUE TITLE
Banning static imports

### ISSUE THREAD

**Issue by chamacs** [skuzzle/restrict-imports-enforcer-rule#13]
I tried using this to ban static imports:
`import static org.testng.Assert.*`

It doesn't fail as I had expected.  Does the plugin currently support static imports?

Maybe my configuration is wrong.  My POM plugin configuration:
`			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>3.0.0-M2</version>
				<dependencies>
					<dependency>
						<groupId>de.skuzzle.enforcer</groupId>
						<artifactId>restrict-imports-enforcer-rule</artifactId>
						<version>0.9.0</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>assert-excludes</id>
						<phase>process-sources</phase>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<restrictImports
									implementation="de.skuzzle.enforcer.restrictimports.RestrictImports">
									<reason>Ensure TestNG Assertions are not beeing used</reason>
									<bannedImport>org.testng.Assert.*</bannedImport>
								</restrictImports>
							</rules>
						</configuration>
					</execution>
				</executions>
			</plugin>`

Thanks.

UPDATE:  After looking at the source code, I can get it to work by doing this:
`<bannedImport>static org.testng.Assert.*</bannedImport>`

Was this the intended way to ban static imports?
Thanks again.

**Comment by skuzzle** [comment]
Great that you worked out how to match static imports. Actually I haven't thought about this use case at all and I'm not quite sure what the best way would be. Currently, I have two ideas:
1. Leave it the way it is. This would make banned static imports very explicit in the plugin's configuration but it also feels a little hacky to me (maybe that is just because my code currently doesn't care about whitespaces in the package patterns).
2. Always match static imports by default, without requiring the users to explicitly specify the 'static' keyword in the pattern.

Not quite sure what would be better. Either way, I'll update the docs to mention how to match static imports for now.

**Comment by skuzzle** [comment]
Version 0.10.0 will have native support for variant 1. It will basically behave like now, but the behavior is explicitly coded in. There are also strong checks for syntactic correct package names (check whether every used character is a valid java identifier character)
